title: reverie baroque
description: Website for Early Music group, reverie baroque
baseurl: "/reverie_baroque"
theme: minima

minima:
  include_custom_css: true

header_pages:
  - about.md
  - members.md
  - programmes.md
  - schedule.md
  - watch_listen.md
  - contact.md
